### PR TITLE
 localization for Nexchange

### PR DESCRIPTION
**Pull request by MKTHINGS**
Added a moment locale for easy translations, so user/admin will be able to easy change language for their translations

### CODE REVIEW

**Comment by BeOleg** [comment]
Hello @MKTHINGS we do have an ongoing effort on enabling i18n on Nexchange, but can you please elaborate what is the advantage of using localised Moment.js as JS time is always local.

Is it about time formatting (i.e. dd-mm-yyyy in EU opposed to mm-dd-yyyy in the USD?).
If that is the case, I will ask @punit2502 to cherry pick your commit into his upcoming i18n PR

**Comment by MKTHINGS** [comment]
Hi @BeOleg, no, it only concerns the translation of the days, months and a few moments ago relating to recent orders.
A user different than the English language and less experienced could find it useful to change the language easily finding in the code its location and changing it with its language of belonging, it would have a result like that:
image

**Comment by BeOleg** [comment]
If @superkarolis is ok with this we can merge this contribution.
Thank you for your contribution @MKTHINGS

**Comment by MKTHINGS** [comment]
@superkarolis, thanks! See you onboard :-)

**Pull request merged**
