### PR TITLE
Check if white label to filter fiat currencies.

### PR DESCRIPTION
**Pull request by murilob**
Check if referral code has value in order to filter fiat currencies of the list.

### CODE REVIEW

**Comment by BeOleg** [comment]
Good solution 👍 
We will also check the request origin from the backend at some point to avoid sending those in the first place.


@superkarolis what do you think?

**Comment by BeOleg** [comment]
@murilob are you going to implement the feedback from @superkarolis or should we?

**Comment by murilob** [comment]
@beoleg i’ll do it

**Comment by murilob** [comment]
@BeOleg @superkarolis Done!

**Comment by superkarolis** [comment]
I merged this commit into a separate PR as there was an extra case where no referral is set that needed to be handled.

**Pull request merged**
