### PR TITLE
Updated testimonials to lastest trustpilot reviews - when clicked all…

### PR DESCRIPTION
**Pull request by mrtrader1313**
Updated to new and latest testimonials from Trustpilot 
All testimonials clicked are linked to https://www.trustpilot.com/review/n.exchange page.

### CODE REVIEW

**Comment by punit2502** [comment]
@mrnexchange Can you please update review urls to:

1. https://www.trustpilot.com/reviews/5eb6830525e5d209b8e607cc
2. https://www.trustpilot.com/reviews/5ea5b5ce086b6409bc8e391d
3. https://www.trustpilot.com/reviews/5ee3d7687dd753070882162b

**Comment by mrtrader1313** [comment]
doing

**Comment by BeOleg** [comment]
@mrtrader1313 is it done?

**Comment by punit2502** [comment]
@mrtrader1313 can your run the below command to re-run tests?

git commit --amend --no-edit
git push origin testimonials -f

**Comment by mrtrader1313** [comment]
Hi, I did it please check

**Comment by mrtrader1313** [comment]
Punit it shifted to the one without links update!

**Comment by mrtrader1313** [comment]
@BeOleg @punit2502 Now its fixed and I think it can be merged. tests re-run as well

**Pull request merged**
